#!/bin/sh

. /etc/update-motd.d/colors

cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[ "$cores" -eq "0" ] && cores=1
threshold="${cores:-1}.0"

echo

if [ $(echo "`cut -f1 -d ' ' /proc/loadavg` < $threshold" | bc) -eq 1 ]; then
    python /etc/update-motd.d/sysinfo.py
else
    echo " System information disabled due to load higher than $threshold"
fi
upSeconds=`/usr/bin/cut -d. -f1 /proc/uptime`
secs=$(($upSeconds%60))
mins=$(($upSeconds/60%60))
hours=$(($upSeconds/3600%24))
days=$(($upSeconds/86400))
UPTIME=`printf "%d days, %02dh %02dm %02ds " "$days" "$hours" "$mins" "$secs"`
ipprive=`/sbin/ifconfig | /bin/grep "broadcast" | awk '{print $2}'`
ippub=`wget -q -O - http://icanhazip.com/ | tail`
freemem=$((`cat /proc/meminfo | grep MemFree | awk {'print $2'}`/1024))
totalmem=$((`cat /proc/meminfo | grep MemTotal | awk {'print $2'}`/1024))
runps=`ps ax | wc -l | tr -d " "`
date +"%A, %e %B %Y, %R"
uname -srmo
echo "
	-------------------------------------------------------------------
	Date		 :	22222222
	Up time 	 :	$UPTIME
	System 		 :	Ubuntu Bionic with Armbian Linux 4.19.62-sunxi
	System load  :	1.18 0.44 0.16
	Processes	 :	$runps
	Memory usage :	$freemem MB (Free) of $totalmem MB (Total) =  7 %
	CPU temp	 :	27°C
	Usage of /	 :	10% of 15G
	IP Addresses :	$ipprive / $ippub
	-------------------------------------------------------------------
"
printf "\n"
